### ISSUE TITLE
What's color of your skin?

### ISSUE THREAD

**Issue by AnotherAnkor** [jcmellado/js-handtracking#7]
http://itmages.ru/image/view/5222455/bfe9639f
http://itmages.ru/image/view/5222461/0a778268
you removed my previous post. Look here.

**Comment by jcmellado** [comment]
Your previous issue is still there:
https://github.com/jcmellado/js-handtracking/issues/6
Instead of opening a new one, you could add more comments on it.

Skin detection is simple, the color or the pixels must fall inside of a fixed range of values. Take a look at the project web, play with the HT.Skinner.prototype.mask function, or search for a different algorithm in the web, there a lot of out there on the Internet.
